<?php

/**
 * @file
 * Module install logic.
 */

/**
 * Implements hook_install().
 */
function opigno_simple_ui_install() {
  db_update('system')
    ->fields(array('weight' => 10))
    ->condition('name', 'opigno_simple_ui')
    ->execute();

  module_load_include('inc', 'opigno', 'modules/simple_ui/includes/opigno_simple_ui.install');
  opigno_simple_ui_change_quiz_question_bundles_names();

  if (module_exists('quiz')) {
    module_load_include('inc', 'opigno', 'modules/simple_ui/includes/opigno_simple_ui.quiz');
    opigno_simple_ui_update_quiz_labels();
  }
}
