<?php

/**
 * @file
 * The Opigno Simple UI module simplifies the platform interface by providing shortcuts
 * and hiding unnecessary complexity.
 */

/**
 * Implements hook_menu_alter().
 */
function opigno_simple_ui_menu_alter(&$items) {
  // Change the default node tabs on a course node.
  unset($items['node/%node/view']['title']);
  $items['node/%node/view']['title callback'] = 'opigno_simple_ui_course_view_tab_title';
  $items['node/%node/view']['title arguments'] = array(1);
  unset($items['node/%node/edit']['title']);
  $items['node/%node/edit']['title callback'] = 'opigno_simple_ui_course_edit_tab_title';
  $items['node/%node/edit']['title arguments'] = array(1);
  unset($items['node/%/group']['title']);
  $items['node/%/group']['title callback'] = 'opigno_simple_ui_course_group_tab_title';
  $items['node/%/group']['title arguments'] = array(1);

  // Add a new secondary tab "Members".
  $items['node/%/group/users'] = $items['group/%/%/admin/people'];
  $items['node/%/group/users']['title'] = "Members";
  $items['node/%/group/users']['title callback'] = 't';
  unset($items['node/%/group/users']['title arguments']);
  $items['node/%/group/users']['page arguments'][0] = 'node';
  $items['node/%/group/users']['page arguments'][1] = 1;
  $items['node/%/group/users']['access arguments'][1] = 'node';
  $items['node/%/group/users']['access arguments'][2] = 1;
  $items['node/%/group/users']['type'] = MENU_DEFAULT_LOCAL_TASK;

  // Add a new secondary tab "Add members".
  $items['node/%/group/add'] = $items['group/%/%/admin/people/add-user'];
  $items['node/%/group/add']['page arguments'][1] = 'node';
  $items['node/%/group/add']['page arguments'][2] = 1;
  $items['node/%/group/add']['access arguments'][1] = 'node';
  $items['node/%/group/add']['access arguments'][2] = 1;
  $items['node/%/group/add']['type'] = MENU_LOCAL_TASK;

  if (isset($items['group/%/%/admin/people/mass-add-user'])) {
    // Add a new secondary tab "Add members".
    $items['node/%/group/mass-add'] = $items['group/%/%/admin/people/add-user'];
    $items['node/%/group/mass-add']['title'] = "Add multiple members";
    $items['node/%/group/mass-add']['page arguments'][1] = 'node';
    $items['node/%/group/mass-add']['page arguments'][2] = 1;
    $items['node/%/group/mass-add']['access arguments'][1] = 'node';
    $items['node/%/group/mass-add']['access arguments'][2] = 1;
    $items['node/%/group/mass-add']['type'] = MENU_LOCAL_TASK;
  }

  // Make parent tab point to "Members" page.
  $items['node/%/group']['page callback'] = $items['node/%/group/users']['page callback'];
  $items['node/%/group']['page arguments'] = $items['node/%/group/users']['page arguments'];
}

/**
 * Implements hook_modules_installed().
 */
function opigno_simple_ui_modules_installed($modules) {
  module_load_include('inc', 'opigno_simple_ui', 'includes/opigno_simple_ui.install');
  opigno_simple_ui_change_quiz_question_bundles_names();
}

/**
 * Change the "View" tab title on course node pages.
 *
 * @param  stdClass $node
 *
 * @return string
 */
function opigno_simple_ui_course_view_tab_title($node) {
  if ($node->type == OPIGNO_COURSE_BUNDLE) {
    return t('Home');
  }
  return t('View');
}

/**
 * Change the "Edit" tab title on course node pages.
 *
 * @param  stdClass $node
 *
 * @return string
 */
function opigno_simple_ui_course_edit_tab_title($node) {
  if ($node->type == OPIGNO_COURSE_BUNDLE) {
    return t('Settings');
  }
  return t('Edit');
}

/**
 * Change the "Group" tab title on course node pages.
 *
 * @param  stdClass $node
 *
 * @return string
 */
function opigno_simple_ui_course_group_tab_title($node) {
  return t('Users');
}
