<?php

/**
 * @file
 * Opigno SCORM API.
 */

define('OPIGNO_SCORM_DIRECTORY', variable_get('opigno_scorm_directory', variable_get('file_default_scheme', 'public') . '://opigno_scorm_extracted'));

/**
 * Helper function to save SCORM package information.
 *
 * @param object $scorm
 *
 * @return bool
 */
function opigno_scorm_scorm_save($scorm) {
  if (!empty($scorm->id)) {
    return db_update('opigno_scorm_packages')
      ->fields((array) $scorm)
      ->condition('id', $scorm->id)
      ->execute();
  }
  else {
    $id = db_insert('opigno_scorm_packages')
      ->fields((array) $scorm)
      ->execute();

    $scorm->id = $id;

    return !!$id;
  }
}

/**
 * Helper function to load SCORM package information.
 *
 * @param int $fid
 *
 * @return object|false
 */
function opigno_scorm_scorm_load($fid) {
  return db_select('opigno_scorm_packages', 'o')
    ->fields('o', array())
    ->condition('fid', $fid)
    ->execute()
    ->fetchObject();
}

/**
 * Helper function to delete a SCORM package information.
 *
 * @param object $scorm
 */
function opigno_scorm_scorm_delete($scorm) {
  db_delete('opigno_scorm_packages')
    ->condition('id', $scorm->id)
    ->execute();

  // @todo Delete all SCOs as well.
}

/**
 * Helper function to save SCO information.
 *
 * @param object $sco
 *
 * @return bool
 */
function opigno_scorm_sco_save($sco) {
  if (!empty($sco->id)) {
    return db_update('opigno_scorm_package_scos')
      ->fields((array) $sco)
      ->condition('id', $sco->id)
      ->execute();
  }
  else {
    $id = db_insert('opigno_scorm_package_scos')
      ->fields((array) $sco)
      ->execute();

    $sco->id = $id;

    return !!$id;
  }
}

/**
 * Helper function to load SCO information.
 *
 * @param int $id
 *
 * @return object|false
 */
function opigno_scorm_sco_load($id) {
  return db_select('opigno_scorm_package_scos', 'o')
    ->fields('o', array())
    ->condition('id', $id)
    ->execute()
    ->fetchObject();
}

/**
 * Helper function to load SCO information by SCORM id.
 *
 * @param int $scorm_id
 *
 * @return object|false
 */
function opigno_scorm_sco_load_by_scorm_id($scorm_id) {
  return db_select('opigno_scorm_package_scos', 'o')
    ->fields('o', array())
    ->condition('scorm_id', $scorm_id)
    ->execute()
    ->fetchObject();
}

/**
 * Helper function to delete a SCO package information.
 *
 * @param object $sco
 */
function opigno_scorm_sco_delete($sco) {
  db_delete('opigno_scorm_package_scos')
    ->condition('id', $sco->id)
    ->execute();

  // @todo Delete all SCOs as well.
}
