<?php

/**
 * @file
 * Opigno SCORM UI.
 */

/**
 * Implements hook_field_info().
 */
function opigno_scorm_ui_field_info() {
  return array(
    'opigno_scorm_package' => array(
      'label' => t('SCORM package'),
      'description' => t("This field allows users to upload SCORM packages"),
      'settings' => array(
        'display_field' => 0,
        'display_default' => 0,
        'uri_scheme' => variable_get('file_default_scheme', 'public'),
      ),
      'instance_settings' => array(
        'file_extensions' => 'zip',
        'file_directory' => 'opigno_scorm',
        'max_filesize' => '',
        'description_field' => 0,
      ),
      'default_widget' => 'file_generic',
      'default_formatter' => 'opigno_scorm_player',
    ),
  );
}

/**
 * Implements hook_field_widget_info_alter().
 */
function opigno_scorm_ui_field_widget_info_alter(&$info) {
  $info['file_generic']['field types'] = array_merge($info['file_generic']['field types'], array('opigno_scorm_package'));
}

/**
 * Implements hook_field_formatter_info().
 */
function opigno_scorm_ui_field_formatter_info() {
  return array(
    'opigno_scorm_player' => array(
      'label' => t('SCORM player'),
      'field types' => array('opigno_scorm_package'),
    ),
  );
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function opigno_scorm_ui_field_formatter_info_alter(&$info) {
  foreach(array('file_default', 'file_url_plain') as $formatter) {
    $info[$formatter]['field types'][] = 'opigno_scorm_package';
  }
}

/**
 * Implements hook_field_is_empty().
 */
function opigno_scorm_ui_field_is_empty($item, $field) {
  return file_field_is_empty($item, $field);
}

/**
 * Implements hook_field_load().
 */
function opigno_scorm_ui_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  file_field_load($entity_type, $entities, $field, $instances, $langcode, $items, $age);
}

/**
 * Implements hook_field_presave().
 */
function opigno_scorm_ui_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  file_field_presave($entity_type, $entity, $field, $instance, $langcode, $items);
}

/**
 * Implements hook_field_insert().
 */
function opigno_scorm_ui_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
  module_load_include('inc', 'opigno_scorm', 'includes/opigno_scorm.manifest');
  file_field_insert($entity_type, $entity, $field, $instance, $langcode, $items);
  foreach ($items as $item) {
    opigno_scorm_extract($item['fid']);
  }
}

/**
 * Implements hook_field_update().
 */
function opigno_scorm_ui_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  module_load_include('inc', 'opigno_scorm', 'includes/opigno_scorm.manifest');
  file_field_update($entity_type, $entity, $field, $instance, $langcode, $items);
  foreach ($items as $item) {
    $scorm = opigno_scorm_scorm_load($item['fid']);
    if (empty($scorm->id)) {
      opigno_scorm_extract($item['fid']);
    }
  }
}

/**
 * Implements hook_field_delete().
 */
function opigno_scorm_ui_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  file_field_delete($entity_type, $entity, $field, $instance, $langcode, $items);
}

/**
 * Implements hook_field_delete_revision().
 */
function opigno_scorm_ui_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, &$items) {
  file_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, $items);
}

/**
 * Implements hook_field_formatter_view().
 */
function opigno_scorm_ui_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'opigno_scorm_player':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'p',
          '#value' => 'FILE',
        );
      }
      break;
  }

  return $element;
}